package com.tadpole.cloud.product.modular.productproposal.enums;

import lombok.Getter;

/**
 * @author: ljx
 * @description: 提案阶段
 * @date: 2022/7/21
 */
@Getter
public enum RdProposalEnum {
    TA_SYS_DEFAULT_CODE("系统"),
    TA_SYS_DEFAULT_NAME("系统"),

    TA_PAGE_NEW("新增"),
    TA_PAGE_EDIT("编辑"),
    TA_STATE_NEW("新提案"),
    TA_STATE_ARCH("已归档"),
    TA_PROCESS_DESIGN("设计中"),
    TA_PROCESS_SAMPLE("拿样中"),
    TA_PROCESS_ORDER("定品中"),
    TA_PROCESS_ARCHIVE("已归档"),
    TA_ARCH_TYPE_APPR("审批归档"),
    TA_ARCH_TYPE_REVOKE("撤销归档"),
    TA_UPLOAD_DESIGN("提案编辑"),

    SAMPLE_FUNC_SAVE("保存"),
    SAMPLE_FUNC_PUBLIC("发布"),
    SAMPLE_FUNC_DELETE("删除"),
    SAMPLE_PAGE_NEW("新增"),
    SAMPLE_PAGE_EDIT("编辑"),
    SAMPLE_STATE_WAIT_PUBLIC("待发布"),
    SAMPLE_STATE_SAMPLE("拿样中"),
    SAMPLE_STATE_CLOSE("已关闭"),
    SAMPLE_PROCESS_WAIT_PUBLIC("待发布"),
    SAMPLE_PROCESS_WAIT_FEBK("采购反馈中"),
    SAMPLE_PROCESS_WAIT_APP("定制申请中"),
    SAMPLE_PROCESS_WAIT_CONT("合同处理中"),
    SAMPLE_PROCESS_WAIT_APPR("待审批"),
    SAMPLE_PROCESS_WAIT_SAMP("拿样中"),
    SAMPLE_PROCESS_WAIT_CLOSE("已关闭"),
    SAMPLE_METHOD_SPOT_SAMPLE("现货拿样"),
    SAMPLE_METHOD_CUST_SAMPLE("定制拿样"),
    SAMPLE_CLOSE_AUTO("自动关闭"),
    SAMPLE_CLOSE_MANUAL("手动关闭"),

    KFY_STATE_WAIT_SUBMIT("待提交"),
    KFY_STATE_WAIT_DEV_USE("待开发领用"),
    KFY_STATE_IN_EVALUATE("测评中"),
    KFY_STATE_TO_RETURN("待归还"),
    KFY_STATE_TO_BE_DISPOSED("待处置"),
    KFY_STATE_LOST("已报失"),
    KFY_STATE_RETURNED("已退货"),
    KFY_STATE_DESTROYED("已销毁"),
    KFY_STATE_SEALED("已封存"),
    KFY_STATE_USE("领用中"),
    KFY_STATE_RECEIVE("已接收"),
    KFY_LABEL_PRINT_YES("已打印"),
    KFY_LABEL_PRINT_NO("未打印"),
    KFY_FEE_SOURCE_DSC("直接拿样"),
    KFY_FEE_SOURCE_SPA("购样申请"),
    KFY_FEE_SOURCE_CA("定制申请"),
    KFY_IS_TAKE_TO_YES("是"),
    KFY_IS_TAKE_TO_NO("否"),
    KFY_FEBK_IS_VALID_YES("有效"),
    KFY_FEBK_IS_VALID_NO("无效"),
    KFY_REF_METHOD_NORMAL("正常"),
    KFY_REF_METHOD_REPORTING_LOSS("报损"),
    KFY_REF_METHOD_REPORT_LOSS("报失"),
    KFY_FUNC_SAVE("保存"),
    KFY_FUNC_SUBMIT("提交"),
    KFY_FUNC_DELETE("删除"),
    KFY_FUNC_PRINT("打印条码"),
    KFY_FUNC_PUR_LOSS("采购报失"),
    KFY_FUNC_LOSS("报失"),
    KFY_FUNC_PUR_DESTROY("采购销毁"),
    KFY_FUNC_DESTROY("销毁"),
    KFY_FUNC_RETURN("退货"),
    KFY_FUNC_SIGN("签收"),
    KFY_FUNC_FEEDBACK("反馈"),
    KFY_FUNC_COLLECT("收回"),
    KFY_FUNC_RECEIVE("接收"),
    KFY_FUNC_USE("领用"),
    KFY_FUNC_DEPOSIT("封存"),

    KFY_PAGE_NEW("新增"),
    KFY_PAGE_EDIT("编辑"),
    KFY_SC_SUPPLIER("供应商"),
    KFY_SC_ALI("1688网站"),
    KFY_SC_TB("淘宝网站"),
    KFY_SOURCE_XH("现货"),
    KFY_SOURCE_DZ("定制"),
    KFY_SAMPLE_USE_LEVEL_WKF("未开封"),
    KFY_SAMPLE_USE_LEVEL_YKF("已开封"),
    KFY_SAMPLE_USE_LEVEL_YSH("已损坏"),
    KFY_INV_STATUS_EMPTY("-"),
    KFY_INV_STATUS_NO("未年检"),
    KFY_INV_STATUS_YES("已年检"),


    CF_STATUS_WAIT_SUBMIT("待提交"),
    CF_STATUS_WAIT_DEV_FB("待开发反馈"),
    CF_STATUS_DEV_FB("开发已反馈"),
    CF_FUNC_SAVE("保存"),
    CF_FUNC_SUBMIT("提交"),
    CF_PAGE_NEW("新增"),
    CF_PAGE_EDIT("编辑"),
    CF_DEV_RESULT_YES("采纳"),
    CF_DEV_RESULT_NO("不采纳"),
    CF_IS_MOLD_OPEN_YES("是"),
    CF_IS_MOLD_OPEN_NO("否"),
    CF_IS_REFUND_YES("是"),
    CF_IS_REFUND_NO("否"),

    SA_AP_STATU_CTBU("待上传合同"),
    SA_AP_STATU_PA("待审批"),
    SA_AP_STATU_CPR("合同待审核"),
    SA_AP_STATU_CBU("待更新合同"),
    SA_AP_STATU_TBP("待支付"),
    SA_AP_STATU_COMPLETED("已完结"),
    SA_AUDIT_RESULT_YES("同意"),
    SA_AUDIT_RESULT_NO("不同意"),
    SA_APP_RESULT_YES("同意"),
    SA_APP_RESULT_NO("不同意"),
    SA_APP_RESULT_UPDATE_CONTRACT("修订合同"),

    PA_FEE_APP_STATUS_WAIT_SUBMIT("待提交"),
    PA_FEE_APP_STATUS_WAIT_APP("待审核"),
    PA_FEE_APP_STATUS_WAIT_APPR("待审批"),
    PA_FEE_APP_STATUS_WAIT_UPLOAD("待上传"),
    PA_FEE_APP_STATUS_WAIT_PAY("待支付"),
    PA_FEE_APP_STATUS_WAIT_SUPPLY("待补充"),
    PA_FEE_APP_STATUS_PAY("已支付"),
    PA_FEE_APP_STATUS_CANCEL("已撤销"),
    PA_FEE_APP_STATUS_ARCH("已归档"),
    PA_FUNC_SAVE("保存"),
    PA_FUNC_APP("申请"),
    PA_FUNC_SUBMIT("提交"),
    PA_PAGE_NEW("新增"),
    PA_PAGE_EDIT("编辑"),
    PA_FEE_APP_AUDIT_RESULT_YES("同意"),
    PA_FEE_APP_AUDIT_RESULT_NO("不同意"),
    PA_FEE_APP_AUDIT_RESULT_WAIT("待定"),
    PA_FEE_APP_APP_RESULT_YES("同意"),
    PA_FEE_APP_APP_RESULT_NO("不同意"),
    PA_FEE_APP_APP_RESULT_WAIT("待定"),
    PA_FEE_APP_SUPPLIER_IR_YES("是"),
    PA_FEE_APP_SUPPLIER_IR_NO("否"),


    REF_APP_STATUS_CNM("待退款-条件未达成"),
    REF_APP_STATUS_CM("待退款-条件已达成"),
    REF_APP_STATUS_PRC("待退款确认"),
    REF_APP_STATUS_TBSA("待指定账户"),
    REF_APP_STATUS_TUV("待上传凭证"),
    REF_APP_STATUS_RI("退款失效"),
    REF_APP_STATUS_TBP("待打印"),
    REF_APP_STATUS_PCV("待验资"),
    REF_APP_STATUS_RC("退款已确认"),
    REF_FEE_TYPE_GYF("开发样-购样费"),
    REF_FEE_TYPE_DYF("开发样-打样费"),
    REF_FEE_TYPE_KMF("开发样-开模费"),
    FEE_APP_SOURCE_GYSQ("购样申请"),
    FEE_APP_SOURCE_DZSQ("定制申请"),
    REF_ACTUAL_REF_RESULT_DR("直接退款"),
    REF_ACTUAL_REF_RESULT_OD("订单扣款"),
    REF_ACTUAL_REF_RESULT_RP("退款失效-提案失败"),
    REF_ACTUAL_REF_RESULT_RO("退款失效-其它"),
    REF_ACCOUNT_TYPE_PA("提供个人账户账号"),
    REF_ACCOUNT_TYPE_CA("提供公司账户账号"),
    REF_TYPE_FIRST_ORDER("首单退款"),
    REF_TYPE_ORDER_QTY("订单量退款"),
    REF_TYPE_ORDER_AMOUNT("订单金额退款"),

    MOF_STATUS_WAIT_SUBMIT("待提交"),
    MOF_STATUS_WAIT_REVIEW("待审核"),
    MOF_STATUS_WAIT_PRINT("待打印"),
    MOF_STATUS_WAIT_PAY("待付款"),
    MOF_STATUS_WAIT_UPLOAD("待上传票据"),
    MOF_STATUS_WAIT_APPR("待复核"),
    MOF_STATUS_ARCH("已归档"),
    MOF_FUNC_SAVE("保存"),
    MOF_FUNC_SUBMIT("提交"),
    MOF_PAGE_NEW("新增"),
    MOF_PAGE_EDIT("编辑"),
    MOF_APP_DIRECT("直接申请"),
    MOF_APP_CREATE("创建申请"),
    MOF_AUDIT_YES("通过"),
    MOF_AUDIT_NO("不通过"),
    MOF_REVIEW_YES("通过"),
    MOF_REVIEW_NO("不通过"),

    SAEA_STATUS_WAIT_SUBMIT("待提交"),
    SAEA_STATUS_WAIT_REVIEW("待审核"),
    SAEA_STATUS_WAIT_PRINT("待打印"),
    SAEA_STATUS_WAIT_PAY("待付款"),
    SAEA_STATUS_ARCH("已归档"),
    SAEA_AUDIT_RESULT_YES("通过"),
    SAEA_AUDIT_RESULT_BACK("退回"),

    CP_STATUS_WAIT_SUBMIT("待提交"),
    CP_STATUS_WAIT_APPR1("待一级审批"),
    CP_STATUS_WAIT_APPR2("待二级审批"),
    CP_STATUS_APPR("已审批"),
    CP_FUNC_SAVE("保存"),
    CP_FUNC_SUBMIT("提交"),
    CP_PAGE_NEW("新增"),
    CP_PAGE_EDIT("编辑"),
    CP_PAGE_APPR("审批"),
    CP_APPR_RESULT_JXTASJ("继续提案设计"),
    CP_APPR_RESULT_TYLD("同意落地"),
    CP_APPR_RESULT_ZZKF("终止开发"),
    CP_IS_CUST_PRODUCT_YES("是"),
    CP_IS_CUST_PRODUCT_NO("否"),
    CP_IS_SELECT_YES("是"),
    CP_IS_SELECT_NO("否"),


    INV_STATUS_ING("盘点中"),
    INV_STATUS_END("已完结"),
    INV_DISPOSAL_RESULT_SAVE("封存中"),
    INV_DISPOSAL_RESULT_LOSS("已报失"),
    INV_DISPOSAL_RESULT_DES("已销毁")
    ;


    /**
     * 海外仓入库管理签收状态
     */
    private String name;

    RdProposalEnum(String name) {
        this.name = name;
    }

}
