server:
  port: ${SERVER_PORT}

spring:
  application:
    name: bsc-cloud-supplyChain
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  cloud:
    nacos:
      discovery:
        server-addr: ${REGISTER_HOST}
        enabled: true
        register-enabled: true
        watch-delay: 1000
        namespace: test
        username: test
        password: test

ribbon:
  eager-load:
    enabled: true
    # 多个服务用逗号隔开
    clients: roses-account

feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        # NONE不记录任何日志--BASIC仅请求方法URL,状态码执行时间等--HEADERS在BASIC基础上记录header等--FULL记录所有
        loggerLevel: full
        connectTimeout: 500  #连接超时时间
        readTimeout: 5000    #连接超时时间
        errorDecoder: cn.stylefeng.guns.cloud.libs.cloud.feign.GunsFeignErrorDecoder
        requestInterceptors:
          - cn.stylefeng.guns.cloud.libs.cloud.feign.GunsFeignHeaderProcessInterceptor
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

mybatis-plus:
  mapper-locations:
    - classpath*:com/tadpole/cloud/supplyChain/modular/**/mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      table-underline: true

roses:
  scanner:
    app-code: bsc-cloud-supplyChain
    app-name: 供应链管理
    open: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#金蝶webapi配置信息
k3webapi:
  acctid: 6413e63118d690
  username: Administrator
  appid: 218235_R71ITbhH4kn904Wox17oyzSsSs7bTsnu
  appsec: 02ffb8b4c5bc43ec95198ae0aa61ae3d
  serverurl: http://192.168.0.93/k3cloud/

#仓储物流订单生成前缀
logistics:
  order:
    env: DEV
    expires-in-value: 86400

#物流实际结算smb地址
smb:
  url: 192.168.30.31
  username: G20180067
  password: I4e176