server:
  port: ${SERVER_PORT}

spring:
  application:
    name: bsc-cloud-platformSettlement
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  cloud:
    nacos:
      discovery:
        server-addr: ${REGISTER_HOST}
        enabled: true
        register-enabled: true
        watch-delay: 1000
        namespace: test
        username: test
        password: test

ribbon:
  eager-load:
    enabled: true
    # 多个服务用逗号隔开
    clients: roses-account

feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        # NONE不记录任何日志--BASIC仅请求方法URL,状态码执行时间等--HEADERS在BASIC基础上记录header等--FULL记录所有
        loggerLevel: full
        connectTimeout: 500  #连接超时时间
        readTimeout: 5000    #连接超时时间
        errorDecoder: cn.stylefeng.guns.cloud.libs.cloud.feign.GunsFeignErrorDecoder
        requestInterceptors:
          - cn.stylefeng.guns.cloud.libs.cloud.feign.GunsFeignHeaderProcessInterceptor
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

mybatis-plus:
  mapper-locations:
    - classpath*:com/tadpole/cloud/platformSettlement/modular/**/mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      table-underline: true

roses:
  scanner:
    app-code: bsc-cloud-platformSettlement
    app-name: 平台结算
    open: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

ftpRemotePath: \MCMS TEST\

# 文件存储服务器
file:
  path: /mcms_dev

rediskey:
  confirmListing: CONFIRM_LISTING_DEV
  confirmUsd: CONFIRM_USD_DEV
  confirmNoAdjust: CONFIRM_NO_ADJUST_DEV
  confirmNoStation: CONFIRM_NO_STATION_DEV
  confirmManualAdjust: CONFIRM_MANUAL_ADJUST_DEV
  confirmOutsiteFee: CONFIRM_OUTSITE_FEE_DEV
  confirmStationAuto: CONFIRM_STATION_AUTO_DEV
  confirmStationManual: CONFIRM_STATION_MANUAL_DEV
  confirmSubsidy: CONFIRM_SUBSIDY_DEV
  confirmSettlement: CONFIRM_SETTLEMENT_DEV

# 动态表空间名称
warehouse_database: WAREHOUSE_TEST
finance_database: FINANCE_TEST