server:
  port: ${SERVER_PORT}

spring:
  application:
    name: bsc-cloud-externalSystem
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  cloud:
    nacos:
      discovery:
        server-addr: ${REGISTER_HOST}
        enabled: true
        register-enabled: true
        watch-delay: 1000
        namespace: test
        username: test
        password: test

ribbon:
  eager-load:
    enabled: true
    # 多个服务用逗号隔开
    clients: roses-account

feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        # NONE不记录任何日志--BASIC仅请求方法URL,状态码执行时间等--HEADERS在BASIC基础上记录header等--FULL记录所有
        loggerLevel: full
        connectTimeout: 500  #连接超时时间
        readTimeout: 5000    #连接超时时间
        errorDecoder: cn.stylefeng.guns.cloud.libs.cloud.feign.GunsFeignErrorDecoder
        requestInterceptors:
          - cn.stylefeng.guns.cloud.libs.cloud.feign.GunsFeignHeaderProcessInterceptor
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

mybatis-plus:
  mapper-locations:
    - classpath*:com/tadpole/cloud/externalSystem/modular/**/mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      table-underline: true

roses:
  scanner:
    app-code: bsc-cloud-externalSystem
    app-name: 第三方对接服务
    open: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#金蝶erp接口地址
k3cloud:
  ipaddress: http://192.168.0.93/K3Cloud/Gateway?BillType=
  username: 邓亚良
  password: dyl1030
  #ipaddress: http://192.168.2.19:8086/K3Cloud/Gateway?BillType=
  #username: 刘叶凤
  #password: 123456

  adminUsername: Administrator
  adminPassword: BSC|JC2018-6

#金蝶webapi配置信息
k3webapi:
  acctid: 6413e63118d690
  username: Administrator
  appid: 218235_R71ITbhH4kn904Wox17oyzSsSs7bTsnu
  appsec: 02ffb8b4c5bc43ec95198ae0aa61ae3d
  serverurl: http://192.168.0.93/k3cloud/

#领星配置信息
lingxing:
  addr: https://openapi.lingxing.com
  app-id: ak_eXEnouhCXONvR
  app-secret: jmQkzRX6RkmSRULV2GtZJg==
  business-prefix-url: erp/sc
  expires-in-value: 300
  lingxing-auth-token-prefix: LINGXING_AUTH_TOKEN_
  timeout: 30000

mabang:
  url: https://gwapi.mabangerp.com/api/v2
  sec: ec84d32f9485c917980f1b5ddfb3687a
  appkey: 200687
  version: 1
  loginUrl: private.mabangerp.com

saihu:
  baseUrl: https://openapi.sellfox.com
  client_secret: 5a3961f3-c3dc-494f-91a5-063323aeb823
  client_id: 367791
  grant_type: client_credentials


#EBMS提供接口地址
ebms:
  server: http://192.168.2.174:8083
  timeout: 60000
objectLogger:
  serverAddress: http://127.0.0.1:12301
  businessAppName: ObjectLoggerServer
  autoLogAttributes: true