server:
  port: 8002

spring:
  application:
    name: bsc-cloud-externalSystem
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: oracle.jdbc.OracleDriver # Oracle数据库驱动包
    url: jdbc:oracle:thin:@oracleyw.jcintergl.com:1521/ORCLPDB1
    username: basecloud
    password: BaseIP49C
  redis:
    host: 192.168.0.231
    port: 6379
    password: Jin@Cache001
    database: 12
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.231:8848
        enabled: true
        register-enabled: true
        watch-delay: 1000
        namespace: ee8d3a56-9f37-43de-a4d9-c2ba8c01e699
        username: nacos
        password: nacos

ribbon:
  eager-load:
    enabled: true
    # 多个服务用逗号隔开
    clients: roses-account

feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        # NONE不记录任何日志--BASIC仅请求方法URL,状态码执行时间等--HEADERS在BASIC基础上记录header等--FULL记录所有
        loggerLevel: full
        connectTimeout: 30000  #毫秒时间，建立连接的超时时间，一般只在发现服务时用到
        readTimeout: 600000    #毫秒时间 ，接口请求的超时时间
        errorDecoder: cn.stylefeng.guns.cloud.libs.cloud.feign.GunsFeignErrorDecoder
        requestInterceptors:
          - cn.stylefeng.guns.cloud.libs.cloud.feign.GunsFeignHeaderProcessInterceptor
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

mybatis-plus:
  mapper-locations:
    - classpath*:com/tadpole/cloud/externalSystem/modular/**/mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      table-underline: true

roses:
  scanner:
    app-code: bsc-cloud-externalSystem
    app-name: 第三方对接服务
    open: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#金蝶erp接口地址
k3cloud:
  ipaddress: http://192.168.2.19:8086/K3Cloud/Gateway?BillType=
  username: 邓亚良
  password: dyl1030
  #ipaddress: http://192.168.2.19:8086/K3Cloud/Gateway?BillType=
  #username: 刘叶凤
  #password: 123456

  adminUsername: Administrator
  adminPassword: BSC|JC2018-6

#金蝶webapi配置信息
k3webapi:
  acctid: 5ec3c36931de51
  username: Administrator
  appid: 230229_w+0D3bvt3JmZx9xJT72P3d0NRIRZXpst
  appsec: bf2acb72e9ab48ffb632c824497c8894
  serverurl: http://192.168.0.18:8086/k3cloud/
  loginurl: http://192.168.0.18:8086/K3Cloud/html5/index.aspx?ud=
#领星配置信息
lingxing:
  addr: https://openapi.lingxing.com
  app-id: ak_eXEnouhCXONvR
  app-secret: jmQkzRX6RkmSRULV2GtZJg==
  business-prefix-url: erp/sc
  expires-in-value: 300
  lingxing-auth-token-prefix: LINGXING_AUTH_TOKEN_
  timeout: 30000

mabang:
  url: https://gwapi.mabangerp.com/api/v2
  sec: ec84d32f9485c917980f1b5ddfb3687a
  appkey: 200687
  version: 1
  loginUrl: https://private.mabangerp.com

saihu:
  baseUrl: https://openapi.sellfox.com
  client_secret: 5a3961f3-c3dc-494f-91a5-063323aeb823
  client_id: 367791
  grant_type: client_credentials

oa:
  url: http://192.168.0.190
  appid: ssss

#EBMS提供接口地址
ebms:
  server: http://192.168.0.41:8081
  getDeptList: /api/DepartmentFunction/GetDeptList
  category: /api/MaterialCategoryTree/QueryMaterialCategory
  operationCategory: /api/MaterialCategoryTree/QueryMaterialOperationCategory
  saleBrand: /api/ComSaleBrand/GetSaleBrand
  userInfo: /api/User/GetUser
  materiel: /api/ComMateriel/GetMateriel
  categoryTree: /api/MaterialCategoryTree/QueryMaterialCategoryTree
  comMatBrandClass: /api/ComMateriel/GetComMatBrandClass
  comMatModelClass: /api/ComMateriel/GetComMatModelClass
  comMatColorClass: /api/ComMateriel/GetComMatColorClass
  comMatSizeClass: /api/ComMateriel/GetComMatSizeClass
  comMatPackQtyClass: /api/ComMateriel/GetComMatPackQtyClass
  comMatCompatibleModelClass: /api/ComMateriel/GetComMatCompatibleModelClass
  comMatFestLabelClass: /api/ComMateriel/GetComMatFestLabelClass
  comMaterielTree: /api/ComMateriel/GetTbComMaterielAttrTree
  syncMateriel: /api/ComMateriel/SyncMateriel
  syncMaterielStatus: /api/ComMateriel/SyncMaterielStatus
  syncMaterielOtherStatus: /api/ComMateriel/SyncMaterielOtherStatus
  printSampleLabel: http://192.168.106.200:8012/api/ComMateriel/PrintSampleLabel
  timeout: 60000
  loginUrl: http://192.168.0.41

objectLogger:
  serverAddress: http://127.0.0.1:12301
  businessAppName: ObjectLoggerServer
  autoLogAttributes: true